question_data = [
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
      "question": "In Norse mythology, Thor once dressed as a woman.", "correct_answer": "True",
      "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                        "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
                                        "incorrect_answers": ["True"]},
     {"category": "Geography", "type": "boolean", "difficulty": "easy",
      "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                       "question": "There is a city called Rome in every continent on Earth.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
      "question": "The 'Squaring the Circle' problem is solvable.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                       "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
      "question": "According to Greek Mythology, Zeus can control lightning.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
      "question": "The card game 'Munchkin' won the 2001 Origins Award for Best Traditional Card Game.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Politics", "type": "boolean", "difficulty": "easy",
      "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
      "question": "Deadpool&#039;s identity is Slade Wilson.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                       "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
      "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                        "question": "The Windows ME operating system was released in the year 2000.",
                                        "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
      "question": "According to Greek Mythology, Atlas was an Olympian God.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                       "question": "One of Barack Obama's United States presidential campaign slogan's was 'Yes We Can'.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Pokemon, Arbok evolves into Seviper.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                       "question": "'Minions' was released on the June 10th, 2015.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Geography", "type": "boolean", "difficulty": "easy", "question": "Tokyo is the capital of Japan.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as"
                  " 'the Zone'.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
      "question": "An equilateral triangle always has every angle measuring 60&deg;.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "The shotgun appears in every numbered Resident Evil game.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In 'Space Station 13',  the station has a clown aboard it.", "correct_answer": "True",
      "incorrect_answers": ["False"]}]

